# Generated by Django 5.0.7 on 2024-09-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='description',
            new_name='descripcion',
        ),
    ]
