# Generated by Django 5.0.7 on 2024-09-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_rename_description_debate_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='abierto',
        ),
        migrations.AddField(
            model_name='debate',
            name='tipo',
            field=models.CharField(choices=[('1', 'Abierto'), ('0', 'Cerrado')], default='1', max_length=1),
        ),
    ]
