# Generated by Django 5.0.7 on 2024-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0003_remove_debate_abierto_debate_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
